name: RaphaelJenni/FirebaseUI-Angular
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

env:
  NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: checkout
        uses: actions/checkout@v4.1.0
      - run: npm ci --legacy-peer-deps
      - run: npm run build-lib
      - run: npm publish ./dist/firebaseui-angular-library
        if: github.ref_type == 'tag'
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
