name: RaphaelJenni/FirebaseUI-Angular
on:
  push:
    branches:
      - 'master'
      - 'convert-raphaeljenni-firebaseui-angular-to-actions-20231014-094149'

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
env:
  NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: checkout
        uses: actions/checkout@v4.1.0
#      - run: apt-get -y install g++-4.8
      - run: npm ci
      - run: npm run build-lib
      - run: cd dist/firebaseui-angular-library
      - run: npm publish
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
#    strategy:
#      matrix:
#        CXX:
#          - g++-4.8
#    env:
#      CXX: "${{ matrix.CXX }}"
